import Link from "next/link"
import { ArrowUpRight, Github, MoveLeft } from "lucide-react"

const projects = [
  { title: "Credit Card OCR", category: "Computer vision", repo: "https://github.com/cedric190703/Credit_Card_OCR", context: "Pipeline de vision par ordinateur pour lire une carte bancaire depuis une image.", detail: "Le projet corrige la perspective, isole les groupes de chiffres et utilise OpenCV, Tesseract et une approche CNN autour de la police OCR-A. Une étape de détection de fraude est prévue dans l’architecture.", stack: ["Python", "OpenCV", "Tesseract", "CNN"] },
  { title: "Ovarian Cancer Segmentation", category: "Medical AI", repo: "https://github.com/cedric190703/Ov-health-challenge", context: "Projet mené à deux pour la compétition de segmentation médicale pinkcc en France.", detail: "Des modèles distincts pour la tumeur et les métastases sont combinés par vote d’ensemble. Le pipeline couvre augmentation, validation croisée, évaluation et visualisation des prédictions. Score final : 0,5082 sur la métrique Dilated Dice / F2.", stack: ["Python", "TensorFlow", "Ensemble learning", "Medical imaging"] },
  { title: "Local Chat", category: "Local LLM", repo: "https://github.com/cedric190703/local-chat", context: "Interface pour interagir avec plusieurs modèles de langage exécutés localement via Ollama.", detail: "Le produit rassemble chat, RAG, import de fichiers et d’images, amélioration de prompts, blocs de code, état de connexion et expérimentation de recherche web. L’objectif est de conserver un usage flexible, privé et local des LLM.", stack: ["TypeScript", "Next.js", "Ollama", "LangChain"] },
  { title: "RAG Chatting UI", category: "Retrieval-augmented generation", repo: "https://github.com/cedric190703/RAG-chatting-UI", context: "Application locale pour interroger ses propres documents.", detail: "Les fichiers PDF, DOCX et TXT sont chargés, découpés, vectorisés avec les embeddings Ollama et indexés dans FAISS. La réponse conversationnelle affiche les extraits sources pour rendre le contexte vérifiable.", stack: ["Python", "Streamlit", "FAISS", "LangChain"] },
  { title: "Robot Manager UI", category: "Robotics", repo: "https://github.com/cedric190703/Robot-Manager-UI", context: "Application full-stack de pilotage des bras robotiques LeRobot SO-101 et SO-100.", detail: "L’interface gère les ports USB et les caméras, guide la calibration, propose la téléopération, l’enregistrement d’épisodes, le rejeu de trajectoires et la gestion de jeux de données. Le backend FastAPI est séparé d’un frontend React typé.", stack: ["TypeScript", "React", "FastAPI", "LeRobot"] },
  { title: "OfflineLingo", category: "Edge AI", repo: "https://github.com/cedric190703/EDTH-Hackathon-Berlin2026-OfflineLingo", context: "Outil Android de traduction parole-vers-texte pour les opérations d’urgence transfrontalières.", detail: "La transcription et la traduction fonctionnent sur l’appareil, sans cloud, avec des contrôles adaptés au terrain, un glossaire d’urgence, des indicateurs de confiance et un affichage lisible sous pression. Le projet a été réalisé au European Defense Tech Hackathon de Berlin.", stack: ["Kotlin", "Android", "On-device AI", "Speech-to-text"] },
  { title: "Good News Agent", category: "Multi-agent systems", repo: "https://github.com/cedric190703/NewsAgent", context: "Plateforme qui produit des newsletters personnalisées depuis des sources web et RSS.", detail: "Le pipeline LangGraph planifie les angles de recherche, répartit la collecte, évalue pertinence, fraîcheur, crédibilité et signal journalistique, vérifie les faits puis compose la newsletter. Il inclut aussi la gestion des abonnés et la diffusion email.", stack: ["Python", "FastAPI", "LangGraph", "React"] },
  { title: "Gemmory", category: "Private AI", repo: "https://github.com/cedric190703/hackathon-gemma4-gemmory", context: "Coffre de mémoire IA local-first pour Android, avec Gemma 4 exécuté sur l’appareil.", detail: "Notes, conversations, réponses, backlinks et graphe de connaissances restent dans le stockage privé du téléphone. Le projet traite l’installation et la vérification du modèle, l’inférence en streaming, la persistance Room et l’absence de repli cloud.", stack: ["Kotlin", "Android", "Gemma 4", "LiteRT-LM"] },
  { title: "Ship Image Classification", category: "Machine learning", repo: "https://github.com/cedric190703/Image-Classification", context: "CNN conçu pour une compétition Kaggle interne avec une limite de moins de 30 couches.", detail: "L’architecture TensorFlow / Keras combine augmentation de données, BatchNorm, régularisation L2, apprentissage progressif et suivi de validation. Résultat : Top 3 sur 117 équipes, avec un score de validation de 0,87174.", stack: ["Python", "TensorFlow", "Keras", "CNN"] },
]

export default function ShowcasePage() {
  return <main className="hub-page">
    <header className="hub-header"><Link href="/"><MoveLeft size={16} />Retour au portfolio</Link><a href="https://github.com/cedric190703" target="_blank" rel="noreferrer"><Github size={16} />GitHub</a></header>
    <section className="hub-hero"><p>PROJECT SHOWCASE</p><h1>Projets, <em>en détail.</em></h1><div><p>Une sélection de projets personnels, académiques et de hackathons. Chaque fiche donne le problème, le périmètre du travail et les choix techniques documentés dans le dépôt associé.</p><span>09 projets documentés</span></div></section>
    <section className="showcase-grid">{projects.map((project, index) => <article className="showcase-card" key={project.title}><div className="showcase-meta"><span>{String(index + 1).padStart(2, "0")} / {project.category}</span><a href={project.repo} target="_blank" rel="noreferrer" aria-label={`Voir ${project.title} sur GitHub`}><ArrowUpRight size={19} /></a></div><h2>{project.title}</h2><p className="showcase-context">{project.context}</p><p className="showcase-detail">{project.detail}</p><div className="showcase-footer"><div>{project.stack.map((item) => <span key={item}>{item}</span>)}</div><a href={project.repo} target="_blank" rel="noreferrer">Voir le dépôt</a></div></article>)}</section>
    <footer className="hub-footer"><span>© 2026 Cédric Brzyski</span><Link href="/">Portfolio principal</Link></footer>
  </main>
}
