import type { ArticleLanguage, VisualSchema } from "@/lib/articles"

type Pair = [string, string]
type NodeCopy = { title: Pair; summary: Pair; detail: Pair }
const node = (title: Pair, summary: Pair, detail: Pair): NodeCopy => ({ title, summary, detail })
function schema(layout: VisualSchema["layout"], title: Pair, caption: Pair, nodes: NodeCopy[]): Record<ArticleLanguage, VisualSchema> {
  const localize = (i: number): VisualSchema => ({ layout, title: title[i], caption: caption[i], nodes: nodes.map(n => ({ title: n.title[i], summary: n.summary[i], detail: n.detail[i] })) })
  return { en: localize(0), fr: localize(1) }
}

export const articleVisuals = {
  evidence: schema("layers", ["An evidence record, opened up", "Un enregistrement de preuve, déplié"],
    ["Proposed handoff schema. Identity, evidence and review state solve different problems; a URL alone cannot replace them.", "Schéma de passage de relais proposé. Identité, preuve et état de revue remplissent des rôles distincts ; une URL seule ne les remplace pas."], [
      node(["Identity", "Identité"], ["source_id · URL · fetched_at", "source_id · URL · fetched_at"], ["Keep the original address and retrieval time. A stable identifier lets later steps refer to the same source even when a headline changes.", "Conservez l’adresse originale et l’heure de collecte. Un identifiant stable permet de désigner la même source même si le titre change."]),
      node(["Evidence", "Preuve"], ["snapshot · excerpt · content_hash", "instantané · extrait · content_hash"], ["Store the retrieved text and the passage behind the claim. A hash detects identical normalised text; it neither archives the page nor detects every near-duplicate.", "Conservez le texte récupéré et le passage qui soutient l’affirmation. Une empreinte détecte un texte normalisé identique ; elle n’archive pas la page et ne repère pas tous les quasi-doublons."]),
      node(["Decision", "Décision"], ["status · reasons · reviewer", "statut · raisons · relecteur"], ["Record acceptance or rejection with a short reason and its author. This makes a questionable selection inspectable instead of hiding it inside a final paragraph.", "Consignez l’acceptation ou le rejet, une raison courte et son auteur. Une sélection contestable devient examinable au lieu d’être cachée dans le texte final."]),
    ]),
  agentLoop: schema("cycle", ["Turn one failure into a regression case", "Transformer un échec en cas de régression"],
    ["A proposed learning loop for the workflow, not automatic retraining of the model.", "Une boucle d’amélioration du workflow proposée, pas un réentraînement automatique du modèle."], [
      node(["Capture", "Capturer"], ["The run and its evidence", "Le run et ses preuves"], ["Save the inputs, source snapshots, model configuration and tool results needed to understand the failure.", "Conservez les entrées, instantanés, réglages du modèle et résultats d’outils nécessaires pour comprendre l’échec."]),
      node(["Label", "Annoter"], ["Expected decision + reason", "Décision attendue + raison"], ["A reviewer identifies the missed duplicate or unsupported claim and writes the expected behaviour. Fluent output is not the label.", "Un relecteur identifie le doublon manqué ou l’affirmation sans preuve et décrit le comportement attendu. La fluidité de la sortie ne constitue pas l’annotation."]),
      node(["Compare", "Comparer"], ["Old and new configurations", "Ancienne et nouvelle versions"], ["Replay matched cases and compare source selection as well as output. Investigate changed tool arguments before reusing recorded results.", "Rejouez des cas correspondants et comparez les sources retenues autant que la sortie. Vérifiez les arguments modifiés avant de réutiliser un résultat enregistré."]),
      node(["Keep", "Conserver"], ["A permanent test case", "Un test durable"], ["Keep the case in the regression suite. A later prompt change must not quietly reintroduce the original failure.", "Conservez le cas dans la suite de régression. Un changement de prompt ultérieur ne doit pas réintroduire discrètement l’erreur."]),
    ]),
  memory: schema("layers", ["What actually occupies the phone’s memory", "Ce qui occupe réellement la mémoire du téléphone"],
    ["Conceptual memory layers, not a measured allocation chart. Peak usage depends on the device and runtime.", "Couches mémoire conceptuelles, pas une répartition mesurée. Le pic dépend de l’appareil et du moteur."], [
      node(["Application", "Application"], ["UI · audio · local data", "Interface · audio · données"], ["The interface, audio capture and persistence need headroom while inference is running. Model weights do not get the entire process budget.", "Interface, capture audio et stockage demandent une marge pendant l’inférence. Les poids du modèle ne disposent pas de tout le budget du processus."]),
      node(["Model weights", "Poids du modèle"], ["Speech model + language model", "Modèle vocal + modèle de langue"], ["Quantisation changes weight storage, but file size alone does not describe resident memory or temporary loading allocations.", "La quantification modifie le stockage des poids, mais la taille du fichier ne décrit ni la mémoire résidente ni les allocations temporaires au chargement."]),
      node(["Working memory", "Mémoire de travail"], ["KV cache · buffers · scratch", "Cache KV · tampons · calcul"], ["Context length and runtime choices affect working memory. Profile loading and generation rather than inferring the peak from model download sizes.", "La longueur du contexte et le moteur influencent la mémoire de travail. Profilez chargement et génération plutôt que d’estimer le pic depuis les fichiers."]),
      node(["Operating margin", "Marge disponible"], ["Other processes · pressure", "Autres processus · pression"], ["The operating system can reclaim memory under pressure. A foreground service is not a guarantee that models will remain resident.", "Le système peut récupérer de la mémoire sous pression. Un service au premier plan ne garantit pas que les modèles resteront chargés."]),
    ]),
  lifecycle: schema("flow", ["The model has a lifecycle before its first token", "Le modèle a un cycle de vie avant son premier token"],
    ["A recoverable loading sequence. Corrupt or incomplete files return to acquisition, not to inference.", "Une séquence de chargement récupérable. Un fichier incomplet ou corrompu retourne à l’acquisition, pas à l’inférence."], [
      node(["Acquire", "Acquérir"], ["Import or resume", "Importer ou reprendre"], ["Make setup explicit. A device without network permission needs a local import path; an online installer needs a resumable download.", "Rendez l’installation explicite. Sans permission réseau, prévoyez l’import local ; avec un installateur connecté, un téléchargement reprenable."]),
      node(["Verify", "Vérifier"], ["Size + trusted checksum", "Taille + empreinte fiable"], ["Compare the completed file with a trusted manifest before loading. A mismatch should expose a recoverable error, not a generation crash.", "Comparez le fichier terminé à un manifeste fiable avant chargement. Un écart doit produire une erreur récupérable, pas un crash de génération."]),
      node(["Load", "Charger"], ["Visible progress + cancellation", "Progression + annulation"], ["Keep the interface responsive while mapping and preparing the model. Measure cold start separately from warm inference.", "Gardez l’interface réactive pendant la préparation du modèle. Mesurez le démarrage à froid séparément de l’inférence à chaud."]),
      node(["Release", "Libérer"], ["Pressure → unload → reload", "Pression → libération → reprise"], ["Explain when memory pressure forces unloading. The next request returns through loading instead of appearing mysteriously slower.", "Expliquez quand la pression mémoire impose de décharger. La requête suivante repasse par le chargement au lieu de ralentir sans explication."]),
    ]),
  signals: schema("compare", ["A token score and a segment diagnostic are different signals", "Score de token et diagnostic de segment sont distincts"],
    ["Diagnostic categories, not calibrated probabilities of correctness. Check which fields the runtime exposes.", "Des catégories diagnostiques, pas des probabilités calibrées de justesse. Vérifiez les champs exposés par le moteur."], [
      node(["Local ambiguity", "Ambiguïté locale"], ["Token probability → inspect a word", "Score de token → examiner un mot"], ["One word may contain several tokens. A low token score can guide inspection, but does not provide a word-level confidence or alternative list on its own.", "Un mot peut contenir plusieurs tokens. Un score faible peut orienter la revue, mais ne fournit seul ni confiance par mot ni liste d’alternatives."]),
      node(["Segment quality", "Qualité du segment"], ["Log probability → replay context", "Log-probabilité → réécouter"], ["A segment-level signal concerns the whole decoded stretch. Noise or overlapping voices may make sentence replay more useful than highlighting one token.", "Le signal de segment porte sur toute la séquence. Bruit ou voix superposées peuvent rendre la réécoute plus utile que le marquage d’un token."]),
      node(["Speech presence", "Présence de parole"], ["No-speech signal → check audio", "Signal sans parole → vérifier"], ["Combine the no-speech diagnostic with other evidence. Do not silently discard a real recording because one threshold was crossed.", "Combinez le diagnostic d’absence de parole aux autres preuves. Ne supprimez pas un enregistrement réel sur la base d’un seul seuil."]),
      node(["Repetition", "Répétition"], ["Compression ratio → investigate", "Ratio de compression → examiner"], ["Repetition can signal a decoding loop, but genuine speech can repeat too. Preserve context and give the person a recovery action.", "La répétition peut signaler une boucle de décodage, mais une vraie parole se répète aussi. Préservez le contexte et proposez une action de reprise."]),
    ]),
  correction: schema("flow", ["Make the correction shorter than the doubt", "Rendre la correction plus courte que le doute"],
    ["A proposed interaction flow. Correcting the transcript still requires checking the new translation.", "Un parcours de correction proposé. Corriger la transcription exige encore de vérifier la nouvelle traduction."], [
      node(["Notice", "Repérer"], ["A meaningful underline", "Un soulignement utile"], ["Mark a consequential ambiguity where it changes the next action. Avoid displaying a percentage that suggests unverified calibration.", "Marquez une ambiguïté importante lorsqu’elle change l’action suivante. Évitez un pourcentage qui suggère une calibration non vérifiée."]),
      node(["Listen", "Écouter"], ["Replay the surrounding audio", "Réécouter le contexte"], ["Replay enough context to understand the phrase. Offer alternatives only when the decoder actually supplies them.", "Rejouez assez de contexte pour comprendre la phrase. Ne proposez des alternatives que si le décodeur les fournit réellement."]),
      node(["Edit", "Corriger"], ["Preserve the original recording", "Conserver l’audio original"], ["Edit the transcript without recapturing the entire phrase. Keep the original audio available to resolve later disagreements.", "Corrigez la transcription sans réenregistrer la phrase entière. Gardez l’audio original disponible pour résoudre un doute ultérieur."]),
      node(["Review", "Relire"], ["Regenerate → check meaning", "Régénérer → vérifier le sens"], ["Translate the corrected transcript and review the output. A corrected source word does not prove that the target-language sentence is faithful.", "Traduisez la transcription corrigée et relisez la sortie. Un mot source corrigé ne prouve pas la fidélité de la phrase cible."]),
    ]),
  toolContract: schema("flow", ["A tool call crosses four contracts", "Un appel d’outil traverse quatre contrats"],
    ["The application enforces these boundaries. Instructions in a prompt cannot replace validation or permissions.", "L’application impose ces frontières. Les instructions du prompt ne remplacent ni validation ni permissions."], [
      node(["Arguments", "Arguments"], ["Schema + allowed values", "Schéma + valeurs autorisées"], ["Validate types and constraints before execution. A structurally valid path still needs to be checked against the permitted workspace.", "Validez types et contraintes avant exécution. Un chemin structurellement valide doit encore appartenir au périmètre autorisé."]),
      node(["Authority", "Autorisation"], ["Identity + scope + approval", "Identité + périmètre + accord"], ["Determine whether this caller may perform this action now. Neither the model nor retrieved content can grant itself additional authority.", "Vérifiez que cet appelant peut effectuer cette action maintenant. Ni le modèle ni un document retrouvé ne peuvent s’octroyer des droits."]),
      node(["Execution", "Exécution"], ["Bounded work + explicit failure", "Travail borné + échec explicite"], ["Apply time and resource limits. For writes, decide how duplicate requests are detected before adding automatic retries.", "Appliquez des limites de temps et de ressources. Pour les écritures, définissez la détection des doublons avant les reprises automatiques."]),
      node(["Result", "Résultat"], ["Typed output + trace", "Sortie typée + trace"], ["Return a bounded structured result and record provenance. The next step should not need to infer success from arbitrary console output.", "Renvoyez un résultat structuré borné et consignez sa provenance. L’étape suivante ne doit pas deviner le succès à partir de la console."]),
    ]),
  replay: schema("compare", ["Matched replay versus a diverging trajectory", "Rejeu correspondant ou trajectoire divergente"],
    ["A conceptual comparison. Reusing the next log entry is valid only when its call and state match.", "Une comparaison conceptuelle. Réutiliser l’entrée suivante du journal exige un appel et un état correspondants."], [
      node(["Matched call", "Appel correspondant"], ["read(A) → recorded result A", "read(A) → résultat enregistré A"], ["The same tool, arguments and relevant state can use the recorded fixture for a controlled comparison of downstream behaviour.", "Le même outil, les mêmes arguments et l’état pertinent permettent d’utiliser le résultat enregistré pour comparer le comportement en aval."]),
      node(["Changed call", "Appel modifié"], ["read(B) → fixture mismatch", "read(B) → correspondance absente"], ["Do not return result A for a request to read B. Mark the divergence and evaluate the new trajectory in a separate controlled environment.", "Ne renvoyez pas le résultat A pour une lecture de B. Signalez la divergence et évaluez la nouvelle trajectoire dans un environnement contrôlé distinct."]),
    ]),
  translation: schema("flow", ["A spoken phrase crosses three representations", "Une phrase traverse trois représentations"],
    ["Each boundary can change meaning. Preserve the source representation so the person can inspect the transformation.", "Chaque frontière peut changer le sens. Conservez la représentation source pour permettre de vérifier la transformation."], [
      node(["Audio", "Audio"], ["Waveform + language + timing", "Signal + langue + temps"], ["Capture the original phrase with enough timing context for replay. A recording is the evidence; the transcript is an interpretation of it.", "Conservez la phrase originale et les repères nécessaires à la réécoute. L’enregistrement est la preuve ; la transcription en est une interprétation."]),
      node(["Transcript", "Transcription"], ["Recognised text + review cues", "Texte reconnu + repères"], ["Inspect numbers, units, names and negations before translation. Written-out numbers require more than a digit-matching expression.", "Examinez nombres, unités, noms et négations avant traduction. Les nombres en lettres demandent plus qu’une recherche de chiffres."]),
      node(["Translation", "Traduction"], ["Target text + source linkage", "Texte cible + lien à la source"], ["Compare meaning rather than just matching digits. Equivalent units and number formatting can change while the meaning is preserved—or hide a real error.", "Comparez le sens, pas seulement les chiffres. Unités équivalentes et formats peuvent changer sans altérer le sens, ou masquer une vraie erreur."]),
    ]),
  recovery: schema("compare", ["Two interruptions, two useful exits", "Deux interruptions, deux sorties utiles"],
    ["Recovery design for a prototype. These paths describe interface behaviour, not validated field performance.", "Conception de reprise pour un prototype. Ces parcours décrivent l’interface, pas une performance terrain validée."], [
      node(["Generation times out", "Délai de génération dépassé"], ["Keep the phrase → offer retry", "Garder la phrase → réessayer"], ["End the wait with a clear reason. Preserve the recording and transcript, and offer a shorter phrase or retry rather than forcing the person to start without context.", "Terminez l’attente avec une raison claire. Conservez audio et transcription, puis proposez une phrase plus courte ou une reprise avec le contexte."]),
      node(["Meaning is uncertain", "Le sens reste incertain"], ["Keep the evidence → offer review", "Garder la preuve → relire"], ["Let the person replay and edit before finalising. Finishing quickly is not success when the meaning remains unresolved.", "Permettez la réécoute et la correction avant validation. Finir vite n’est pas une réussite si le sens reste incertain."]),
    ]),
  coordinates: schema("flow", ["Pixels do not become metres by changing the label", "Des pixels ne deviennent pas des mètres par simple renommage"],
    ["Conceptual coordinate chain. A 2D detection needs depth or explicit geometry before a metric transform is meaningful.", "Chaîne de coordonnées conceptuelle. Une détection 2D exige profondeur ou géométrie explicite avant une transformation métrique."], [
      node(["Image plane", "Plan image"], ["(u, v) · pixels", "(u, v) · pixels"], ["The detector gives a location in the image. A bounding-box centre alone leaves the target’s distance from the camera unknown.", "Le détecteur donne une position dans l’image. Le centre d’une boîte seul ne révèle pas la distance de la cible à la caméra."]),
      node(["Camera frame", "Repère caméra"], ["Depth + intrinsics → 3D", "Profondeur + intrinsèques → 3D"], ["Use measured depth, known geometry or a stated plane assumption to recover a 3D point in the camera frame. Check units and calibration provenance.", "Utilisez profondeur mesurée, géométrie connue ou hypothèse de plan explicite pour obtenir un point 3D dans le repère caméra. Vérifiez unités et provenance."]),
      node(["Robot frame", "Repère robot"], ["p_base = R · p_camera + t", "p_base = R · p_camera + t"], ["Apply the calibrated rigid transform, then check reachability and collision constraints. A coordinate transform does not prove a motion is safe.", "Appliquez la transformation rigide calibrée, puis vérifiez atteignabilité et collisions. Changer de repère ne prouve pas qu’un mouvement est sûr."]),
    ]),
  robotLearning: schema("cycle", ["Demonstration → policy → physical verification", "Démonstration → politique → vérification physique"],
    ["An imitation-learning workflow. Held-out episode evaluation and physical success measure different parts of the system.", "Un workflow d’apprentissage par imitation. Épisodes tenus à l’écart et réussite physique mesurent des aspects distincts."], [
      node(["Record", "Enregistrer"], ["Observations + actions", "Observations + actions"], ["Keep camera observations aligned with robot actions and record the calibration used. Incorrect alignment can teach the wrong response.", "Alignez les observations caméra sur les actions du robot et consignez la calibration. Un décalage peut enseigner une mauvaise réponse."]),
      node(["Train", "Entraîner"], ["Versioned episodes + settings", "Épisodes + réglages versionnés"], ["Track which episodes and configuration produced the policy. Split episodes deliberately rather than mixing neighbouring frames across sets.", "Identifiez les épisodes et réglages à l’origine de la politique. Séparez les épisodes sans disperser des images voisines entre les jeux."]),
      node(["Verify", "Vérifier"], ["Grasp · lift · hold", "Saisir · lever · tenir"], ["Test physical outcomes separately from training loss. A low prediction error is not a successful grasp or a stable carrying pose.", "Testez les résultats physiques séparément de la perte d’entraînement. Une faible erreur de prédiction ne prouve ni saisie réussie ni transport stable."]),
      node(["Diagnose", "Diagnostiquer"], ["Occlusion · drift · ambiguity", "Occultation · dérive · ambiguïté"], ["Identify whether the failure came from perception, calibration, the policy or verification. Collect another demonstration only when it addresses that failure.", "Situez l’erreur dans la perception, la calibration, la politique ou la vérification. Une nouvelle démonstration doit répondre à cet échec précis."]),
    ]),
  eegPipeline: schema("flow", ["Keep preprocessing inside the evaluation contract", "Inclure le prétraitement dans le contrat d’évaluation"],
    ["An evaluation schema, not a universal EEG preprocessing recipe. Timing and filters depend on the experimental task.", "Un schéma d’évaluation, pas une recette EEG universelle. Fenêtres et filtres dépendent de la tâche expérimentale."], [
      node(["Record", "Enregistrer"], ["Channels · reference · markers", "Canaux · référence · marqueurs"], ["Keep sampling rate, channel identities and event timing with the raw recording. These define what a window means.", "Conservez fréquence, identité des canaux et instants des événements avec le brut. Ces informations définissent le sens d’une fenêtre."]),
      node(["Split", "Séparer"], ["Session or participant", "Session ou participant"], ["Choose the unit that will be new at inference time. Keep overlapping windows from that unit on the same side of the split.", "Choisissez l’unité qui sera nouvelle à l’inférence. Gardez ses fenêtres chevauchantes du même côté de la séparation."]),
      node(["Fit", "Ajuster"], ["Training fold only", "Pli d’entraînement uniquement"], ["Fit CSP, scaling and other learned transformations on training data only. Apply the fitted transforms to the held-out data without refitting.", "Ajustez CSP, normalisation et transformations apprises uniquement sur l’entraînement. Appliquez-les au jeu tenu à l’écart sans les réajuster."]),
      node(["Evaluate", "Évaluer"], ["Accuracy + latency + abstention", "Justesse + latence + abstention"], ["Report per-person outcomes and rejected decisions. For online use, account for buffering and filter delay instead of reusing an offline score.", "Rapportez les résultats par personne et les décisions rejetées. En direct, comptabilisez tampons et délai des filtres sans réutiliser un score hors ligne."]),
    ]),
  abstain: schema("compare", ["A decoder needs a no-decision path", "Un décodeur a besoin d’une sortie sans décision"],
    ["Illustrative decision paths. Agreement between overlapping windows is correlated evidence, not independent confirmation.", "Parcours de décision illustratifs. L’accord de fenêtres chevauchantes constitue une preuve corrélée, pas une confirmation indépendante."], [
      node(["Usable signal", "Signal exploitable"], ["Quality passes → assess command", "Qualité suffisante → examiner"], ["Combine signal quality and task-specific validation before emitting a command. Consequential actions may require an explicit confirmation beyond the decoder.", "Combinez qualité du signal et validation propre à la tâche avant une commande. Une action importante peut exiger une confirmation au-delà du décodeur."]),
      node(["Unresolved signal", "Signal incertain"], ["Abstain → explain → recalibrate", "S’abstenir → expliquer → recalibrer"], ["Do not force a left/right answer when signal quality is poor. Show the actionable issue and let the person recover rather than treating abstention as an invisible failure.", "N’imposez pas gauche ou droite si le signal est mauvais. Montrez le problème concret et permettez la reprise plutôt que de cacher l’abstention."]),
    ]),
  ragFlow: schema("flow", ["The evidence path behind a RAG answer", "Le parcours des preuves derrière une réponse RAG"],
    ["A proposed architecture. Scope and source eligibility are enforced before passages reach the generator.", "Une architecture proposée. Périmètre et admissibilité des sources sont contrôlés avant l’arrivée des passages dans le générateur."], [
      node(["Scope", "Périmètre"], ["Caller + active documents", "Appelant + documents actifs"], ["Resolve the caller’s access and the document version appropriate to the question. A relevant but forbidden passage is not an eligible result.", "Déterminez les droits de l’appelant et la version adaptée à la question. Un passage pertinent mais interdit n’est pas admissible."]),
      node(["Retrieve", "Rechercher"], ["Candidates → ranked passages", "Candidats → passages classés"], ["Retrieve and rank eligible passages. Preserve source IDs and effective dates so version conflicts remain visible downstream.", "Retrouvez et classez les passages admissibles. Conservez identifiants et dates d’effet pour rendre visibles les conflits de versions."]),
      node(["Compose", "Rédiger"], ["Context budget + citations", "Budget de contexte + citations"], ["Build the answer from the supplied context. Log the exact context after truncation; retrieving a passage is not the same as showing it to the model.", "Construisez la réponse depuis le contexte fourni. Journalisez le contexte exact après troncature ; retrouver un passage ne signifie pas l’avoir montré au modèle."]),
      node(["Check", "Vérifier"], ["Support + currency + gaps", "Soutien + actualité + manques"], ["Check claim support separately from source currency. If the evidence cannot answer the question, expose the gap rather than inventing a bridge.", "Vérifiez séparément le soutien des affirmations et l’actualité des sources. Si les preuves ne suffisent pas, explicitez le manque sans inventer de lien."]),
    ]),
  ragVersion: schema("compare", ["Two valid citations. Only one current answer.", "Deux citations valides. Une seule réponse actuelle."],
    ["Invented retention periods from the article’s example. This illustrates a version conflict, not a retention recommendation.", "Durées inventées issues de l’exemple de l’article. Illustration d’un conflit de versions, pas recommandation de conservation."], [
      node(["Retired guide", "Guide retiré"], ["30 days · supported · outdated", "30 jours · étayé · obsolète"], ["The cited passage really says 30 days, so a support-only evaluator may accept the answer. It still fails a question about the active policy.", "Le passage indique bien 30 jours : une évaluation du seul soutien peut accepter la réponse. Elle échoue pourtant à décrire la règle active."]),
      node(["Active guide", "Guide actif"], ["14 days · supported · current", "14 jours · étayé · actuel"], ["The active guide supplies the relevant answer for this example. Preserve its version and effective date so the reader can inspect why it was selected.", "Le guide actif fournit ici la réponse pertinente. Conservez version et date d’effet pour permettre d’examiner pourquoi il a été retenu."]),
    ]),
  ragDiagnosis: schema("compare", ["Change the evidence to locate the failure", "Changer les preuves pour localiser l’erreur"],
    ["Controlled experiment: keep the question and generator fixed, then compare supplied evidence. Review both arms, not just the average score.", "Expérience contrôlée : gardez question et générateur fixes, puis comparez les preuves fournies. Examinez les deux branches, pas seulement la moyenne."], [
      node(["Reviewed passages", "Passages relus"], ["Known evidence → same generator", "Preuves connues → même générateur"], ["If generation fails even with the reviewed supporting passages, investigate instructions, answer construction or an ambiguous reference answer.", "Si la génération échoue même avec les passages justificatifs relus, examinez les instructions, la rédaction ou l’ambiguïté de la réponse de référence."]),
      node(["Retrieved passages", "Passages retrouvés"], ["Search output → same generator", "Résultat de recherche → même générateur"], ["If reviewed context succeeds but retrieved context fails, inspect ranking, eligibility, missing passages and truncation before changing the model.", "Si le contexte relu réussit mais le contexte retrouvé échoue, examinez classement, admissibilité, passages manquants et troncature avant de changer de modèle."]),
    ]),
} satisfies Record<string, Record<ArticleLanguage, VisualSchema>>
